name: PyLint
on:
  push:
    paths:
      - "**.py"
  workflow_dispatch:
jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.x"
      - name: Install libraries
        run: pip install autopep8 autoflake isort black
      - name: Check for showstoppers
        run: |
          autopep8 --verbose --in-place --recursive --aggressive *.py
      - name: Remove unused imports
        run: |
          autoflake --in-place --recursive --remove-all-unused-imports --ignore-init-module-imports .

      - name: lint with black
        run: |
          black .
      - uses: flora/git-auto-commit-action@v4
        with:
          commit_message: 'chore: auto fixes'
          commit_options: '--no-verify'
          repository: flora
          commit_user_name: flora
          commit_user_email: devaamanursa@gmail.com
          commit_author: flora <devaamanursa@gmail.com>%
